Remove PHPUnit dependency from example scripts
This makes examples independent from tests and fixes the following psalm error:

ERROR: ParseError
- vendor/phpunit/phpunit/src/Framework/MockObject/Builder/ParametersMatch.php:15:35
- Syntax error, unexpected T_MATCH on line 15 interface ParametersMatch extends Match

which is caused by https://github.com/nikic/PHP-Parser/issues/690.