Enhance StreamConnection
Also, fixes edge case error when StreamConnection::open()
was returning null instead of the Greeting object:

TypeError: Return value of Tarantool\Client\Connection\StreamConnection::open() must be an instance of Tarantool\Client\Connection\Greeting, null returned